; This file was auto-generated by drush make
core = 6.x

api = 2
projects[drupal][version] = "6.x"

; Modules
projects[admin][version] = "2.0"

projects[advanced_help][version] = "1.2"

projects[block_class][version] = "1.4"

projects[bulkdelete][version] = "1.3"

projects[computed_field][version] = "1.0"

projects[cck][version] = "2.9"

projects[content_profile][version] = "1.0"

projects[content_taxonomy][version] = "1.0-rc2"

projects[date][version] = "2.9"

projects[devel][version] = "1.27"

projects[features][version] = "1.2"

projects[filefield][version] = "3.10"

projects[google_analytics][version] = "3.3"

projects[hierarchical_select][version] = "3.8"

projects[imageapi][version] = "1.10"

projects[imagecache][version] = "2.0-rc1"

projects[imagecache_profiles][version] = "1.3"

projects[imagefield][version] = "3.10"

projects[jcarousel][version] = "2.6"

projects[jquery_ui][version] = "1.5"

projects[link][version] = "2.9"

projects[menu_block][version] = "2.4"

projects[menu_breadcrumb][version] = "1.3"

projects[menu_editor][version] = "2.2"

projects[path_redirect][version] = "1.0-rc2"

projects[pathauto][version] = "1.6"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[people_profiles_feature][download][type] = ""
projects[people_profiles_feature][download][url] = ""
projects[people_profiles_feature][type] = "module"
projects[people_profiles_feature][version] = "1.1"

projects[search404][version] = "1.12"

projects[token][version] = "1.19"

projects[views][version] = "2.16"

projects[views_bonus][version] = "1.1"

projects[views_slideshow][version] = "2.4"

projects[webform][version] = "3.18"

projects[wysiwyg][version] = "2.4"

; Themes

projects[framework][version] = "2.6"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[research_group_profile_views][download][type] = ""
projects[research_group_profile_views][download][url] = ""
projects[research_group_profile_views][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ses_bookings][download][type] = ""
projects[ses_bookings][download][url] = ""
projects[ses_bookings][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ses_client_sites][download][type] = ""
projects[ses_client_sites][download][url] = ""
projects[ses_client_sites][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ses_custom][download][type] = ""
projects[ses_custom][download][url] = ""
projects[ses_custom][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[wmd4][download][type] = ""
projects[wmd4][download][url] = ""
projects[wmd4][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[wmd4_guest][download][type] = ""
projects[wmd4_guest][download][url] = ""
projects[wmd4_guest][type] = "module"

projects[researchgroup][download][type] = "git"
projects[researchgroup][download][url] = "https://github.com/stanford-earth/d6_researchgroup.git"
projects[researchgroup][type] = "theme"


